# Site settings
email: documentation@cleo.com
url: "https://developer.cleo.com"
baseurl: ""

# No Google analytics yet - FMJ 20160223
#google_analytics:
#  default:
#    id: UA-71308214-1
#  blog:
#    id: UA-71308214-2

permalink: /blog/:year/:month/:day/:title.html
paginate: 5
paginate_path: "/blog/page-:num/"
raml:
  - key_prefix: "api-"
    url_prefix: "api/api-reference/"
    root_file: _raml/api.raml

# Build settings
markdown: kramdown
exclude:
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - LICENSE-CC-BY-40.txt
  - LICENSE-MIT.txt
  - node_modules
  - npm-shrinkwrap.json
  - package.json
  - Rakefile
  - README.md
  - util
include:
  - videos

# Search index settings
search:
  host: localhost:9200
  index:
    name: cleo-docs
    settings:
      mappings:
        page:
          properties:
            url:
              type: string
              analyzer: keyword
            title:
              type: string
              analyzer: english
            content:
              type: string
              analyzer: english
        section:
          properties:
            url:
              type: string
              analyzer: keyword
            title:
              type: string
              analyzer: english
            content:
              type: string
              analyzer: english
